apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: jwt-hmac
spec:
  name: jwt-hmac
  protocol: http
  active: true
  proxy:
    target_url: https://httpbingo.org
    listen_path: /httpbin-jwt
    strip_listen_path: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: aHR0cHM6Ly9sZW11ci0xNS5jbG91ZC1pYW0uY29tL2F1dGgvcmVhbG1zL2Nhcmxvc3R5ay9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC9jZXJ0cw==
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - tyk/jwt-hmac
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-hmac
spec:
  name: jwt-hmac
  state: active
  active: true
  partitions:
    quota: true
    rate_limit: true
  access_rights_array:
    - name: jwt-hmac
      namespace: tyk
      versions:
        - Default
